### ISSUE TITLE
Add light mode

### ISSUE THREAD

**Issue by steve-1507** [Moonlight-Panel/Moonlight#323]
Forcing dark mode makes it very hard to read text in direct sunlight, and removing it served no purpose other than to propagate the use of dark mode. My suggestion is to directly decide what theme to use based on the users device settings.

**Comment by Marcel-Baumgartner** [comment]
As we are very few developers we dont want to implement 2 themes for every feature and making sure they match. And if we dont make sure everything matches perfectly people like you will open 10324 bug reports because of that. Instead of complaining you could contribute to this project. If you would provide changes we can merge to support light mode again we would merge for sure.

**Comment by steve-1507** [comment]
I would be happy to contribute, however, as I've never written C# before, just reading and understanding the source code is very hard for me.
