### ISSUE TITLE
Add databases in normal servers

### ISSUE THREAD

**Issue by faelixyz** [Moonlight-Panel/Moonlight#335]
Add a databases tab in normal servers (NOT webspaces)
tysm!

**Comment by Marcel-Baumgartner** [comment]
The database feature is strictly connected to the webspaces because of cloudpanel. We are NOT pterodactyl. I would appreciate if you would take 5 minutes to think about an feature request before opening a issue

**Comment by faelixyz** [comment]
I thought about it, my question is, why you are mostly so unfriendly? nothing against you  but it's just some facts..

**Comment by faelixyz** [comment]
in the discord talk you are really friendly but not in discord text, github issues, just messages. nothing against you, like i said.

**Comment by Skullians** [comment]
Look.
Masu is one of the few devs working on this panel. They are not a massive group like Pterodactyl is.
Give them a break.
Moonlight is still in heavy development, they are working on some incredibly useful features.

**Comment by faelixyz** [comment]
I didn't want to be mean but I understand every staff member of moonlight and endelon, I really love the hosting panel and endelon itself, but it's just some words that randomly fell out of my mouth. i apologize!

**Comment by Marcel-Baumgartner** [comment]
> I thought about it, my question is, why you are mostly so unfriendly? nothing against you but it's just some facts..

Because of people. People which have no experience in anything wanting to do something and instead of researching for themselves they are just asking me/my team, are unfriendly as fuck and dont even read what we are sending them. I invest a lot of time making this panel and working on endelon, i invest a lot of money in endelon and getting nothing back (except a few nice people). people are just greedy and always wanting more services, resources and features. As you can see in the statistics of this repo, i am doing the most of the work alone. And i cannot take this any more. If people like you wont annoy me all the time and think for themselves instead of asking the shit out of my team and me, i would be nicer. But as this is not changing even after i made a public announchment over the mental state of my team and me, i'll stay pissed when a little script kidde is for example making feature requests without thinking or researching and i will let you know in my texts. the only reason i am nicer in vc than in text is that i only go into vc if i can mentally handle these people.

**Comment by faelixyz** [comment]
Oh, I understand. I'm sorry to bother you:/

**Comment by Marcel-Baumgartner** [comment]
> but it's just some facts..

The fact is that you and other people are like a mental illness to my team and me. We are only reason we are still doing this is because of a few nice people in the community. If you look at the history of team members in endelon you see a comparable fast leaving and joining sequences. Do you want to know why people are leaving endelon team? Because they cannot take it mentally anymore

**Comment by faelixyz** [comment]
I'm sorry!!!!!!

**Comment by faelixyz** [comment]
I'm now shutting up. I seriously didn't mean it like that.
